### ISSUE TITLE
memory error crash

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#112]
> MemoryError on ccwsge0808:8884 in run: std::bad_alloc
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 1070, in run
    while not menu[command]():
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 240, in wrapper
    return func(*args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 1088, in reduce
    result = self._processQueue(context, func, [(index, data)], *args, **kwargs)[0]
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 547, in _processQueue
    return self._reduceQueue(context, None, func, queue, *args, **kwargs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 573, in _reduceQueue
    resultList = [func(self._getCache(context, i), data, *args, **kwargs) for i, data in queue]
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/pool.py", line 573, in <listcomp>
    resultList = [func(self._getCache(context, i), data, *args, **kwargs) for i, data in queue]
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_drivers/17.0.1-5-g0d47de9/python/lsst/pipe/drivers/multiBandDriver.py", line 428, in runMeasurements
    self.measureCoaddSources.runDataRef(dataRef)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/multiBand.py", line 996, in runDataRef
    exposureId=self.getExposureId(patchRef))
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/multiBand.py", line 1041, in run
    self.measurement.run(sources, exposure, exposureId=exposureId)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/sfm.py", line 258, in run
    self.runPlugins(noiseReplacer, measCat, exposure, beginOrder, endOrder)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/sfm.py", line 303, in runPlugins
    self.callMeasure(measChildRecord, exposure, beginOrder=beginOrder, endOrder=endOrder)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/baseMeasurement.py", line 331, in callMeasure
    self.doMeasurement(plugin, measRecord, *args, **kwds)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/baseMeasurement.py", line 361, in doMeasurement
    plugin.measure(measRecord, *args, **kwds)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/meas_base/17.0.1-6-gaad6eea+12/python/lsst/meas/base/wrappers.py", line 43, in measure
    self.cpp.measure(measRecord, exposure)
MemoryError: std::bad_alloc

in /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/run_multiband/010/000/006/logFile.txt

**Comment by johannct** [comment]
Looks like a transient failure, so I should probably just blindly relaunch the stream.
