### ISSUE TITLE
coaddDriver RuntimeError on "No PsfMatched warps were found to build the template"

### ISSUE THREAD

**Issue by johannct** [LSSTDESC/ImageProcessingPipelines#115]
> 119625 WARN  2019-06-16T09:41:27.867+0200 coaddDriver: ccwsge1332:119625: Caught RuntimeError while coadding DataId(initialdata={'tract': 2731, 'filter': 'g', 'patch': '1,6'}, tag=set()): No PsfMatched warps were
 found to build the template coadd which is
            required to run CompareWarpAssembleCoaddTask. To continue assembling this type of coadd,
            first either rerun makeCoaddTempExp with config.makePsfMatched=True or
            coaddDriver with config.makeCoadTempExp.makePsfMatched=True, before assembleCoadd.

            Alternatively, to use another algorithm with existing warps, retarget the CoaddDriverConfig to
            another algorithm like:

                from lsst.pipe.tasks.assembleCoadd import SafeClipAssembleCoaddTask
                config.assemble.retarget(SafeClipAssembleCoaddTask)
        
119625 INFO  2019-06-16T09:41:27.897+0200 coaddDriver: ccwsge1332:119625: Traceback:
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/ctrl_pool/17.0+39/python/lsst/ctrl/pool/parallel.py", line 509, in logOperation
    yield
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_drivers/17.0.1-5-g0d47de9/python/lsst/pipe/drivers/coaddDriver.py", line 300, in coadd
    coaddResults = self.assembleCoadd.runDataRef(patchRef, selectDataList)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_base/17.0.1-2-g3e5d191+31/python/lsst/pipe/base/timer.py", line 150, in wrapper
    res = func(self, *args, **keyArgs)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/assembleCoadd.py", line 515, in runDataRef
    supplementaryData = self.makeSupplementaryData(dataRef, warpRefList=inputData.tempExpRefList)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2019_19/stack/miniconda3-4.5.12-1172c30/Linux64/pipe_tasks/17.0.1-14-g303e8d74/python/lsst/pipe/tasks/assembleCoadd.py", line 2044, in makeSupplementaryData
    raise RuntimeError(self._noTemplateMessage(self.assembleStaticSkyModel.warpType))

This seems to be caught with a WARN rather than a FATAL, and thus does not crash the job.

Present in :
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/021/001/004/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/039/000/000/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/061/007/000/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/068/009/004/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/129/001/002/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/129/003/002/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/137/004/001/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/137/004/002/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/141/000/003/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/148/000/002/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/159/005/001/logFile.txt
- /sps/lsst/users/descprod/Pipeline2/Logs/Run2.1i/v1/DC2DM_DRP/0.41/task_coadd/task_coadd_tract_patch/task_coaddDriver/run_coaddDriver/010/159/009/001/logFile.txt

**Comment by johannct** [comment]
Just before the trace there are three warnings, seemingly related : 

> 119625 WARN  2019-06-16T09:41:27.866+0200 coaddDriver.assembleCoadd.assembleStaticSkyModel: Could not find deepCoadd_psfMatchedWarp DataId(initialdata={'visit': 484325, 'filter': 'g', 'patch': '1,6', 'tract': 273
1}, tag=set()); skipping it
119625 INFO  2019-06-16T09:41:27.866+0200 coaddDriver.assembleCoadd.assembleStaticSkyModel: Found 0 deepCoadd_psfMatchedWarp
119625 WARN  2019-06-16T09:41:27.866+0200 coaddDriver.assembleCoadd.assembleStaticSkyModel: No coadd temporary exposures found

I am surprised that the first WARN here is not enough to bail out gracefully rather than let the trace occur down the line.

**Comment by johannct** [comment]
Reproducing the crash above at the command line, and with the proposed config change : `coaddDriver.py /sps/lsst/dataproducts/desc/DC2/Run2.1i/w_2019_19-v1 --rerun calexp-v1:coadd-test --id tract=2731 patch=1,6 filter=g --selectId visit=484325 detector=40 --doraise --longlog --noExit --cores 1 -c makeCoaddTempExp.makePsfMatched=True`

**Comment by johannct** [comment]
I also see the following in the screen output for this command : 
```
